---
driver:
  name: vagrant
  vagrantfile_erb: Vagrantfile.erb
#  gui: true
  customize:
    cpus: 4
    memory: 6144
#  synced_folders:
#    - ["~/work", "/root/work"]
  network:
    - ["private_network", {ip: "33.33.34.13"}]
  persistent_storage:
    enabled: true
    manage: false
    format: false
    size: 40 * 1024
    location: File.expand_path('~/VirtualBox VMs/dev-lxc-platform.vdi')

provisioner:
  name: chef_zero
  chef_omnibus_install_options: -P chefdk
  chef_omnibus_root: /opt/chefdk

platforms:
  - name: ubuntu-16.10
    driver:
      box: bento/ubuntu-16.10
      box_url: https://atlas.hashicorp.com/bento/boxes/ubuntu-16.10/versions/2.3.1/providers/virtualbox.box

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[ntp]
      - recipe[dev-lxc-platform]
    attributes:
      dev-lxc-platform:
        btrfs_device: /dev/sdb
