---
driver:
  name: vagrant
  vagrantfile_erb: Vagrantfile.erb
#  gui: true
  customize:
    cpus: 4
    memory: 6144
    natdnshostresolver1: "on"
#  synced_folders:
#    - ["..", "/dev-shared"]
  network:
    - ["private_network", {ip: "33.33.34.13"}]
  persistent_storage:
    enabled: true
    manage: false
    format: false
    size: 40 * 1024
    location: File.expand_path('~/VirtualBox VMs/dev-lxc-platform.vdi')

provisioner:
  name: chef_zero
  chef_omnibus_install_options: -P chefdk
  chef_omnibus_root: /opt/chefdk

platforms:
  - name: ubuntu-14.04
    driver:
      box: ubuntu/trusty64
      box_url: https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/14.04/providers/virtualbox.box

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[dev-lxc-platform::btrfs]
      - recipe[dev-lxc-platform::mount-lxc-btrfs]
      - recipe[dev-lxc-platform]
      - recipe[dev-lxc-platform::dev-lxc]
