---
driver:
  name: vagrant
  vagrantfile_erb: Vagrantfile.erb
#  gui: true
  customize:
    cpus: 4
    memory: 6144
    natdnshostresolver1: "on"
#  synced_folders:
#    - ["~/dev", "/root/dev"]
  network:
    - ["private_network", {ip: "33.33.34.13"}]
  persistent_storage:
    enabled: true
    manage: false
    format: false
    size: 40 * 1024
    location: File.expand_path('~/VirtualBox VMs/dev-lxc-platform.vdi')

provisioner:
  name: chef_zero
  chef_omnibus_install_options: -P chefdk
  chef_omnibus_root: /opt/chefdk

platforms:
  - name: ubuntu-15.04
    driver:
      box: opscode-ubuntu-15.04
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-15.04_chef-provisionerless.box

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[ntp]
      - recipe[dev-lxc-platform::fix-ntp]
      - recipe[dev-lxc-platform::btrfs]
      - recipe[dev-lxc-platform::mount-lxc-btrfs]
      - recipe[dev-lxc-platform::mount-lxd-btrfs]
      - recipe[dev-lxc-platform]
      - recipe[dev-lxc-platform::dev-lxc]
