#!chef exec ruby

require 'yaml'
require 'aws-sdk'
require 'thor'

class KitchenInstanceCTL < Thor
  no_commands do
    def get_instance_config(kitchen_instance_file = nil)
      unless File.exist?(kitchen_instance_file)
        puts "ERROR: Kitchen instance file '#{kitchen_instance_file}' does not exist."
        exit 1
      end
      puts "Using kitchen instance file #{kitchen_instance_file}"
      instance_config = YAML.load(IO.read(kitchen_instance_file))
    end

    def get_instance_type(instance_config = nil)
      if instance_config['server_id']
        'ec2'
      elsif instance_config['hostname'] == '127.0.0.1' && instance_config['username'] == 'vagrant'
        'vagrant'
      else
        puts 'ERROR: Unable to determine instance type.'
        exit 1
      end
    end

    def get_ec2_instance(instance_config = nil)
      Aws::EC2::Instance.new(instance_config['server_id'])
    end

    def get_vagrant_instance_path(kitchen_instance_file = nil)
      File.join(Dir.pwd, %w(.kitchen kitchen-vagrant), "kitchen-#{File.basename(Dir.pwd)}-#{File.basename(kitchen_instance_file, '.yml')}")
    end

    def update_kitchen_instance_file_hostname(kitchen_instance_file = nil, i = nil)
      if i.public_dns_name.empty?
        puts "ERROR: Public DNS Name is not set for EC2 instance #{i.id}. Make sure the instance exists and is running."
        puts "Instance #{i.id} is #{i.state.name}"
        exit 1
      end
      puts "Updating the hostname in #{kitchen_instance_file} to #{i.public_dns_name}"
      kitchen_instance = YAML.load(IO.read(kitchen_instance_file))
      kitchen_instance['hostname'] = i.public_dns_name
      IO.write(kitchen_instance_file, kitchen_instance.to_yaml)
    end

    def update_kitchen_instance_file_port(kitchen_instance_file, port)
      if port == 0
        puts 'ERROR: Port is not set for the Vagrant instance. Make sure the instance exists and is running.'
        exit 1
      end
      puts "Updating the port in #{kitchen_instance_file} to '#{port}'"
      kitchen_instance = YAML.load(IO.read(kitchen_instance_file))
      kitchen_instance['port'] = port.to_s
      IO.write(kitchen_instance_file, kitchen_instance.to_yaml)
    end
  end

  desc 'status [PLATFORM_NAME]', 'Print instance state'
  option :file, aliases: '-f', desc: 'Specify a kitchen instance file such as `.kitchen/default-vagrant.yml`'
  def status(platform_name = nil)
    kitchen_instance_file = options[:file] || ".kitchen/default-#{platform_name}.yml"
    instance_config = get_instance_config(kitchen_instance_file)
    case get_instance_type(instance_config)
    when 'ec2'
      i = get_ec2_instance(instance_config)
      puts "EC2 instance #{i.id} is #{i.state.name}"
    when 'vagrant'
      p = get_vagrant_instance_path(kitchen_instance_file)
      puts "Getting status of Vagrant instance at path #{p}"
      Dir.chdir(p) do
        system('vagrant status')
      end
    end
  end

  desc 'start [PLATFORM_NAME]', 'Start instance'
  option :file, aliases: '-f', desc: 'Specify a kitchen instance file such as `.kitchen/default-vagrant.yml`'
  def start(platform_name = nil)
    kitchen_instance_file = options[:file] || ".kitchen/default-#{platform_name}.yml"
    instance_config = get_instance_config(kitchen_instance_file)
    case get_instance_type(instance_config)
    when 'ec2'
      i = get_ec2_instance(instance_config)
      puts "Starting EC2 instance #{i.id}"
      i.start
      i.wait_until_running
      update_kitchen_instance_file_hostname(kitchen_instance_file, i)
    when 'vagrant'
      p = get_vagrant_instance_path(kitchen_instance_file)
      puts "Starting Vagrant instance at path #{p}"
      port = ''
      Dir.chdir(p) do
        system('vagrant up')
        port = `vagrant port --guest 22`
      end
      update_kitchen_instance_file_port(kitchen_instance_file, port.to_i)
    end
  end

  desc 'stop [PLATFORM_NAME]', 'Stop instance'
  option :file, aliases: '-f', desc: 'Specify a kitchen instance file such as `.kitchen/default-vagrant.yml`'
  def stop(platform_name = nil)
    kitchen_instance_file = options[:file] || ".kitchen/default-#{platform_name}.yml"
    instance_config = get_instance_config(kitchen_instance_file)
    case get_instance_type(instance_config)
    when 'ec2'
      i = get_ec2_instance(instance_config)
      puts "Stopping EC2 instance #{i.id}"
      i.stop
      i.wait_until_stopped
    when 'vagrant'
      p = get_vagrant_instance_path(kitchen_instance_file)
      puts "Stopping Vagrant instance at path #{p}"
      Dir.chdir(p) do
        system('vagrant halt --force')
      end
    end
  end
end

KitchenInstanceCTL.start(ARGV)
