#!/bin/sh
#
# Update the hostname in the cloned container's /etc/hosts file
#

# Note that /etc/hostname is updated by lxc itself
if [ -f $LXC_ROOTFS_PATH/etc/hosts ]; then
    sed -i "s|$LXC_SRC_NAME|$LXC_NAME|" $LXC_ROOTFS_PATH/etc/hosts
fi
exit 0
