#!/usr/bin/env bash

if TMUX= tmux new-session -s "containers" -n containers -d; then
    tmux split-window -h -t "containers"
    tmux send-keys -t "containers" "watch -n0.5 free -h" C-m

    tmux split-window -v -t "containers"
    tmux send-keys -t "containers" "watch -n0.5 bash -c xc-ls" C-m

    tmux new-window -a -t "containers" -n shell
fi

tmux select-window -t "containers:containers"

tmux select-pane -t "containers:containers.0"

if ! tmux switch-client -t "containers"; then
    tmux attach -t "containers"
fi
